version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    volumes:
      - ./certs:/app/certs
      - ./config:/app/config
    environment:
      - PORT=8443
      - HOST=0.0.0.0
    restart: unless-stopped
