# OpenRouter LLM Configuration

[llm]
model = "openai/gpt-4o"  # Format is "provider/model"
base_url = "https://openrouter.ai/api/v1"
api_key = "<OPENROUTER_API_KEY>"  # Replace with your OpenRouter API key
api_type = "openrouter"
api_version = ""  # Leave empty for OpenRouter
max_tokens = 4096
temperature = 0.7

# You can also define alternative configurations
[llm.anthropic]
model = "anthropic/claude-3-opus"
api_type = "openrouter"
temperature = 0.5

[llm.mistral]
model = "mistral/mistral-large"
api_type = "openrouter"
temperature = 0.7

[browser]
headless = true

[search]
engine = "Google"
